### ISSUE TITLE
Make countries, states & counties searchable

### ISSUE THREAD

**Issue by HirdayGupta** [octopicorn/covid19-charts#14]
Thanks for this awesome tool! Feature request:

A search bar above each of those columns that filter the results shown would be really useful - especially for counties.

**Comment by octopicorn** [comment]
Thanks @HirdayGupta ! Yes agreed. Can you recommend how this UX should work?
If there is a search bar text input, when you type does it just limit the list below as you type? and then if you see the selection you want among, say, ten items below, you click the one you want, it gets selected, and then - does the searchbar automatically clear out? Or do you have to click on some icon to clear it?

**Comment by thejk1945** [comment]
As in Google auto complete, where the options get narrowed as you type.

**Comment by HirdayGupta** [comment]
@octopicorn thanks for following up! As @thejk1945 mentioned, options getting narrowed as you type would be great. And then when you see what you want and click then yeah it gets selected. I'm not too invested either way - the searchbar can get auto-cleared or there can be some icon. I think the common case would be the autoclear case so maybe that?

**Comment by HirdayGupta** [comment]
Happy to contribute some code to make this happen too if you can give some guidance!

**Comment by octopicorn** [comment]
Thanks - it is done.
