### ISSUE TITLE
add control to show chart data as percentage of population

### ISSUE THREAD

**Issue by octopicorn** [octopicorn/covid19-charts#26]
find a data source for world population that matches the countries we have here

use this to apply a transformation to the timeseries:
newValue = rawValue / countryPopulation

the y axis will now plot between 0 - 100% (or more likely, 0 - 0.001%)

add this control on top row. shrink control fonts a bit to make it fit

**Comment by rhazegh** [comment]
This would be fantastic!

**Comment by octopicorn** [comment]
https://github.com/octopicorn/covid19-charts/pull/35
