### ISSUE TITLE
Include plot new cases vs existing cases

### ISSUE THREAD

**Issue by arula10101** [octopicorn/covid19-charts#29]
In the case of exponential, it is useful to see if the rate of growth is changing. It is a guideline for whether we are winning against the virus or not.
As a suggestion: use weekly moving average.

**Comment by octopicorn** [comment]
@arula10101 do you have any info about this type of visualization?  i have been looking for epidemiology stats websites that explain what it means to show new cases vs existing cases. can't find anything about this specific type.

https://www.cdc.gov/csels/dsepd/ss1978/lesson3/section2.html

it would be helpful to learn more about this so i can share some info with the new visualization

**Comment by arula10101** [comment]
Hello,

This video has a very good explanation:
 https://m.youtube.com/watch?feature=youtu.be&v=54XLXg4fYsc

This article also has some math on exponential growth:
https://www.google.com/amp/s/www.wired.com/story/how-fast-does-a-virus-spread/amp



On Apr 4, 2020, at 23:05, octopicorn <notifications@github.com> wrote:

﻿

@arula10101<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farula10101&data=02%7C01%7C%7C8fcb3ee62bf9479ec44608d7d90e25af%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637216527088456669&sdata=A0VQNtD90KDuwdDmsgte1WqZ7N%2BtdTlX%2BHaBEEtYpG4%3D&reserved=0> do you have any info about this type of visualization? i have been looking for epidemiology stats websites that explain what it means to show new cases vs existing cases. can't find anything about this specific type.

https://www.cdc.gov/csels/dsepd/ss1978/lesson3/section2.html<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cdc.gov%2Fcsels%2Fdsepd%2Fss1978%2Flesson3%2Fsection2.html&data=02%7C01%7C%7C8fcb3ee62bf9479ec44608d7d90e25af%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637216527088466677&sdata=8usf%2B0OHCMGXny1IjkGmkBRe17k%2BYkGaorlbkqGwGc0%3D&reserved=0>

it would be helpful to learn more about this so i can share some info with the new visualization

**Comment by octopicorn** [comment]
@arula10101 this is done. thanks for the links, very helpful!
