### ISSUE TITLE
Maybe per capita option?

### ISSUE THREAD

**Issue by thejk1945** [octopicorn/covid19-charts#32]
Love your work here! For a more appropriate comparison, I'd love to see a per capita option. Especially for deaths.

**Comment by octopicorn** [comment]
Hello! glad to see you here @thejk1945 !!
maybe this is a duplicate of https://github.com/octopicorn/covid19-charts/issues/26 ?
let me know if not

**Comment by thejk1945** [comment]
You know. It is. ;)

**Comment by thejk1945** [comment]
You know, it is.
