### ISSUE TITLE
Percent of population

### ISSUE THREAD

**Issue by JWinawer** [octopicorn/covid19-charts#40]
First, thanks for making this great tool available. 

and now for a question: when I plot percents of population (e.g. confirmed cases in NY), I get values that are greater than 100% (e.g,. 400). Is there an issue with the units? Perhaps it’s  the number per million rather than percent?

Thanks!
Jon

**Comment by octopicorn** [comment]
@JWinawer yes it is (value / (population / 100000) )

just made this change yesterday. i'll update the y axis label to explain it:

https://github.com/octopicorn/covid19-charts/pull/39

without this change, the values were very small, like 0.000001% and it just made yaxis hard to see

**Comment by octopicorn** [comment]
@JWinawer  fixed this. thank you for bringing it up.

https://github.com/octopicorn/covid19-charts/pull/41
