### ISSUE TITLE
add moving average transform

### ISSUE THREAD

**Issue by CarloLucibello** [octopicorn/covid19-charts#44]
In order to smooth out daily increase series, it would be convenient to add a moving average transform on a window of a few days. I suggest using a 3 or 5 days window as default and possibly allow user to modify the value

**Comment by octopicorn** [comment]
Sure. 
Is the moving average to be overlapping?

That is, if i picked 3 days, would we show:

1. Avg(day1, day2, day3), Avg(day 2, day3, day4), ...

Or

2. Avg(day1, day2, day3), Avg(day4, day5, day6)?

Im guessing 1. ?

**Comment by CarloLucibello** [comment]
yep, option 1 is what I would be expecting. Thanks!
