### ISSUE TITLE
Heads up: Data corruption?

### ISSUE THREAD

**Issue by otheus** [octopicorn/covid19-charts#71]
All US-values for 4/29 have been corrupted.  I cannot tell if this is a multiplier, a constant or what. It completely makes any graph meaningless.  Maybe it's a "0" and it makes "new cases" and per-100k graphs look ridiculous.

You might need to fix this in code: if data is missing, the data gets skipped.

**Comment by octopicorn** [comment]
@otheus thank you

**Comment by octopicorn** [comment]
@otheus cannot confirm your issue.
data for 4/29 (US, 1039909 confirmed, 60697 deaths) looks fine to me on website
if you're looking at the website, please do a hard refresh. i had to scrap the cache buster recently and it may be older code? if you're running locally, please share a screenshot

**Comment by otheus** [comment]
@octopicorn Look at any state or county in the US. Values from T-7? are multiplied by -10. I thought problem was also in US too, but maybe .. idk. Verified in separate browser, incognito mode, chrome/guest profile. Today the "Bad" day is 4/30. screenshot:  https://imgur.com/iZGtkXU

**Comment by octopicorn** [comment]
@otheus would have been helpful to specify in your bug report: "there is an issue when looking at `New in Past X Days` when it's set to 1` and country is US". your initial comment said all values for US were bad in general, thank you for clarifying 

yes, this is a known issue. there is a bug calculating "New in Past X Days". 

To get number for past 1 day, you need to enter 2. To get new for past 2 days, you have to enter 3. It is an n+1 type of bug, having to do with the loop used to calculate this.  if it makes you worried the number might be off, you can always verify by switching over to normal view and see that the delta between day x and y are correct. 

Thanks for reporting , thought this was fixed. For now just use the workaround to add +1 to the number of days you actually want. 

bug is located here in code: 
https://github.com/octopicorn/covid19-charts/blob/master/public/js/main.js#L389

**Comment by otheus** [comment]
@octopicorn You're still not seeing the problem!  The data is bad in EVERY view --- just more noticeable in that one.  
![2020-05-06 09_07_05-covid-19 charts](https://user-images.githubusercontent.com/6928226/81146696-125b2780-8f79-11ea-8633-a1d139dbd985.png)
![2020-05-06 09_06_56-covid-19 charts](https://user-images.githubusercontent.com/6928226/81146697-138c5480-8f79-11ea-82c6-ad4912687303.png)
![2020-05-06 09_06_35-covid-19 charts](https://user-images.githubusercontent.com/6928226/81146701-14bd8180-8f79-11ea-89f2-a45028ce56ac.png)
![2020-05-06 09_06_24-covid-19 charts](https://user-images.githubusercontent.com/6928226/81146706-15eeae80-8f79-11ea-8eb9-5fd2cf5dc14f.png)
![2020-05-06 03_27_49-covid-19 charts](https://user-images.githubusercontent.com/6928226/81146709-171fdb80-8f79-11ea-91e2-441cacd0e0ac.png)

**Comment by otheus** [comment]
![2020-05-06 09_06_12-covid-19 charts](https://user-images.githubusercontent.com/6928226/81146752-2e5ec900-8f79-11ea-8b8f-21428bef8fd1.png)
Also here. MIND THE GAP!

**Comment by octopicorn** [comment]
Ok. I see it now.
The problem is not with US the country but with individual states. Looks like 5/1 data went missing. Will rectify this, checking out JH data source 
Thank you.

**Comment by octopicorn** [comment]
@otheus 
found the issue. 
for a couple of days the data files downloaded were just a few bytes and contained only the test `404 Not Found`
this means the issue was caused by the server deciding it's time to download the new day's data, before it is even ready yet. Will wrap some error handling around that piece in server.js to avoid saving any file if a 404 returned
many thanks for your help.

**Comment by otheus** [comment]
Thanks for checking! Your tool is incredibly valuable and I'm trying to raise awareness of its utility. 

Any chance this also happened with Spain on 4/23? France on 4/21 and 4/28? Japan on 4/27.  Italy on 3/11.

**Comment by octopicorn** [comment]
I will check
